import { collection, deleteDoc, doc, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js'; import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js'; import { auth, db, isFirebaseConfigured } from './firebase.js'; import { renderFooter, renderHeader, showToast, esc, money } from './ui.js';
renderHeader('admin');renderFooter();const gate=document.querySelector('#adminGate'),app=document.querySelector('#adminApp');let zones=[],books=[];
function statusOptions(v,id){return `<select data-book-status="${id}" class="select"><option ${v==='pending'?'selected':''} value="pending">Ожидает</option><option ${v==='confirmed'?'selected':''} value="confirmed">Подтверждено</option><option ${v==='completed'?'selected':''} value="completed">Завершено</option><option ${v==='cancelled'?'selected':''} value="cancelled">Отменено</option></select>`}
async function saveZone(z=null){const name=prompt('Название зоны',z?.name||'Arena #');if(!name)return;const price=Number(prompt('Цена за час',z?.price||800));const capacity=Number(prompt('Вместимость',z?.capacity||2));const category=prompt('Категория: ps5 / ps4 / vip',z?.category||'ps5');const data={name,price,capacity,category,console:category==='ps4'?'PlayStation 4 Pro':'PlayStation 5',description:z?.description||'Игровая зона PlayStation',tags:z?.tags||[category.toUpperCase()],status:z?.status||'available',createdAt:z?.createdAt||serverTimestamp()};try{if(z)await updateDoc(doc(db,'zones',z.id),data);else await setDoc(doc(collection(db,'zones')),data);showToast('Зона сохранена.')}catch(e){showToast(e.message)}}
async function removeZone(id){if(!confirm('Удалить игровую зону?'))return;await deleteDoc(doc(db,'zones',id));showToast('Зона удалена.')}
function renderZones(){document.querySelector('#zonesTable').innerHTML=zones.map(z=>`<tr><td><b>${esc(z.name)}</b></td><td>${esc(z.category||'ps5')}</td><td>${money(z.price||0)}</td><td>${z.capacity||2}</td><td><span class="badge ${z.status==='busy'?'red':'green'}">${z.status==='busy'?'Занято':'Свободно'}</span></td><td><button class="btn btn-secondary" data-edit="${z.id}">Изм.</button> <button class="btn btn-ghost" data-del="${z.id}">Удал.</button></td></tr>`).join('')||'<tr><td colspan="6" class="muted">Зон нет</td></tr>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>saveZone(zones.find(z=>z.id===b.dataset.edit)));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>removeZone(b.dataset.del));document.querySelector('#sZones').textContent=zones.length;}
function renderBooks(){document.querySelector('#bookingsTable').innerHTML=books.map(b=>`<tr><td>${esc(b.zoneName||'—')}</td><td>${esc(b.userEmail||b.userId||'—')}</td><td>${esc(b.date||'—')} ${esc(b.time||'')}</td><td>${statusOptions(b.status,b.id)}</td><td>${b.total?money(b.total).replace('/час',''):''}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">Бронирований нет</td></tr>';document.querySelectorAll('[data-book-status]').forEach(s=>s.onchange=async()=>{await updateDoc(doc(db,'bookings',s.dataset.bookStatus),{status:s.value});showToast('Статус изменён.')});document.querySelector('#sBookings').textContent=books.length;document.querySelector('#sActive').textContent=books.filter(x=>!['completed','cancelled'].includes(x.status)).length}
if(!isFirebaseConfigured||!db){gate.innerHTML='<div class="notice">Firebase не подключён. Админка готова, но доступ к данным появится после настройки.</div>';}else onAuthStateChanged(auth,async user=>{if(!user){gate.innerHTML='<div class="notice">Войдите в аккаунт администратора.</div>';return;}onSnapshot(doc(db,'users',user.uid),snap=>{const d=snap.data();if(d?.role!=='admin'){gate.innerHTML='<div class="notice">Доступ разрешён только пользователю с ролью admin.</div>';app.classList.add('hidden');return;}gate.innerHTML='';app.classList.remove('hidden');onSnapshot(query(collection(db,'zones'),orderBy('createdAt','desc')),s=>{zones=s.docs.map(d=>({id:d.id,...d.data()}));renderZones()});onSnapshot(query(collection(db,'bookings'),orderBy('createdAt','desc')),s=>{books=s.docs.map(d=>({id:d.id,...d.data()}));renderBooks()});});});
document.querySelector('#addZoneBtn').onclick=()=>isFirebaseConfigured?saveZone():showToast('Подключите Firebase.');
